// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eshop_rest_api.Data;

#nullable disable

namespace eshop_rest_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251012153437_SyncModel_Seed25")]
    partial class SyncModel_Seed25
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("eshop_rest_api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "Sample 101",
                            ImgUri = "https://placeholder.com/101",
                            Name = "Product 101",
                            Price = 49.90m
                        },
                        new
                        {
                            Id = 102,
                            Description = "Sample 102",
                            ImgUri = "https://placeholder.com/102",
                            Name = "Product 102",
                            Price = 54.90m
                        },
                        new
                        {
                            Id = 103,
                            Description = "Sample 103",
                            ImgUri = "https://placeholder.com/103",
                            Name = "Product 103",
                            Price = 59.90m
                        },
                        new
                        {
                            Id = 104,
                            Description = "Sample 104",
                            ImgUri = "https://placeholder.com/104",
                            Name = "Product 104",
                            Price = 64.90m
                        },
                        new
                        {
                            Id = 105,
                            Description = "Sample 105",
                            ImgUri = "https://placeholder.com/105",
                            Name = "Product 105",
                            Price = 69.90m
                        },
                        new
                        {
                            Id = 106,
                            Description = "Sample 106",
                            ImgUri = "https://placeholder.com/106",
                            Name = "Product 106",
                            Price = 74.90m
                        },
                        new
                        {
                            Id = 107,
                            Description = "Sample 107",
                            ImgUri = "https://placeholder.com/107",
                            Name = "Product 107",
                            Price = 79.90m
                        },
                        new
                        {
                            Id = 108,
                            Description = "Sample 108",
                            ImgUri = "https://placeholder.com/108",
                            Name = "Product 108",
                            Price = 84.90m
                        },
                        new
                        {
                            Id = 109,
                            Description = "Sample 109",
                            ImgUri = "https://placeholder.com/109",
                            Name = "Product 109",
                            Price = 89.90m
                        },
                        new
                        {
                            Id = 110,
                            Description = "Sample 110",
                            ImgUri = "https://placeholder.com/110",
                            Name = "Product 110",
                            Price = 94.90m
                        },
                        new
                        {
                            Id = 111,
                            Description = "Sample 111",
                            ImgUri = "https://placeholder.com/111",
                            Name = "Product 111",
                            Price = 99.90m
                        },
                        new
                        {
                            Id = 112,
                            Description = "Sample 112",
                            ImgUri = "https://placeholder.com/112",
                            Name = "Product 112",
                            Price = 104.90m
                        },
                        new
                        {
                            Id = 113,
                            Description = "Sample 113",
                            ImgUri = "https://placeholder.com/113",
                            Name = "Product 113",
                            Price = 109.90m
                        },
                        new
                        {
                            Id = 114,
                            Description = "Sample 114",
                            ImgUri = "https://placeholder.com/114",
                            Name = "Product 114",
                            Price = 114.90m
                        },
                        new
                        {
                            Id = 115,
                            Description = "Sample 115",
                            ImgUri = "https://placeholder.com/115",
                            Name = "Product 115",
                            Price = 119.90m
                        },
                        new
                        {
                            Id = 116,
                            Description = "Sample 116",
                            ImgUri = "https://placeholder.com/116",
                            Name = "Product 116",
                            Price = 124.90m
                        },
                        new
                        {
                            Id = 117,
                            Description = "Sample 117",
                            ImgUri = "https://placeholder.com/117",
                            Name = "Product 117",
                            Price = 129.90m
                        },
                        new
                        {
                            Id = 118,
                            Description = "Sample 118",
                            ImgUri = "https://placeholder.com/118",
                            Name = "Product 118",
                            Price = 134.90m
                        },
                        new
                        {
                            Id = 119,
                            Description = "Sample 119",
                            ImgUri = "https://placeholder.com/119",
                            Name = "Product 119",
                            Price = 139.90m
                        },
                        new
                        {
                            Id = 120,
                            Description = "Sample 120",
                            ImgUri = "https://placeholder.com/120",
                            Name = "Product 120",
                            Price = 144.90m
                        },
                        new
                        {
                            Id = 121,
                            Description = "Sample 121",
                            ImgUri = "https://placeholder.com/121",
                            Name = "Product 121",
                            Price = 149.90m
                        },
                        new
                        {
                            Id = 122,
                            Description = "Sample 122",
                            ImgUri = "https://placeholder.com/122",
                            Name = "Product 122",
                            Price = 154.90m
                        },
                        new
                        {
                            Id = 123,
                            Description = "Sample 123",
                            ImgUri = "https://placeholder.com/123",
                            Name = "Product 123",
                            Price = 159.90m
                        },
                        new
                        {
                            Id = 124,
                            Description = "Sample 124",
                            ImgUri = "https://placeholder.com/124",
                            Name = "Product 124",
                            Price = 164.90m
                        },
                        new
                        {
                            Id = 125,
                            Description = "Sample 125",
                            ImgUri = "https://placeholder.com/125",
                            Name = "Product 125",
                            Price = 169.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
