// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eshop_rest_api.Data;

#nullable disable

namespace eshop_rest_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251012152611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("eshop_rest_api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "D0",
                            ImgUri = "https://placeholder.com/0",
                            Name = "P0",
                            Price = 58.15m
                        },
                        new
                        {
                            Id = 102,
                            Description = "D1",
                            ImgUri = "https://placeholder.com/1",
                            Name = "P1",
                            Price = 82.37m
                        },
                        new
                        {
                            Id = 103,
                            Description = "D2",
                            ImgUri = "https://placeholder.com/2",
                            Name = "P2",
                            Price = 95.81m
                        },
                        new
                        {
                            Id = 104,
                            Description = "D3",
                            ImgUri = "https://placeholder.com/3",
                            Name = "P3",
                            Price = 82.40m
                        },
                        new
                        {
                            Id = 105,
                            Description = "D4",
                            ImgUri = "https://placeholder.com/4",
                            Name = "P4",
                            Price = 87.63m
                        },
                        new
                        {
                            Id = 106,
                            Description = "D5",
                            ImgUri = "https://placeholder.com/5",
                            Name = "P5",
                            Price = 23.55m
                        },
                        new
                        {
                            Id = 107,
                            Description = "D6",
                            ImgUri = "https://placeholder.com/6",
                            Name = "P6",
                            Price = 6.42m
                        },
                        new
                        {
                            Id = 108,
                            Description = "D7",
                            ImgUri = "https://placeholder.com/7",
                            Name = "P7",
                            Price = 6.92m
                        },
                        new
                        {
                            Id = 109,
                            Description = "D8",
                            ImgUri = "https://placeholder.com/8",
                            Name = "P8",
                            Price = 79.28m
                        },
                        new
                        {
                            Id = 110,
                            Description = "D9",
                            ImgUri = "https://placeholder.com/9",
                            Name = "P9",
                            Price = 91.53m
                        },
                        new
                        {
                            Id = 111,
                            Description = "D10",
                            ImgUri = "https://placeholder.com/10",
                            Name = "P10",
                            Price = 87.65m
                        },
                        new
                        {
                            Id = 112,
                            Description = "D11",
                            ImgUri = "https://placeholder.com/11",
                            Name = "P11",
                            Price = 27.14m
                        },
                        new
                        {
                            Id = 113,
                            Description = "D12",
                            ImgUri = "https://placeholder.com/12",
                            Name = "P12",
                            Price = 45.33m
                        },
                        new
                        {
                            Id = 114,
                            Description = "D13",
                            ImgUri = "https://placeholder.com/13",
                            Name = "P13",
                            Price = 38.63m
                        },
                        new
                        {
                            Id = 115,
                            Description = "D14",
                            ImgUri = "https://placeholder.com/14",
                            Name = "P14",
                            Price = 96.95m
                        },
                        new
                        {
                            Id = 116,
                            Description = "D15",
                            ImgUri = "https://placeholder.com/15",
                            Name = "P15",
                            Price = 92.34m
                        },
                        new
                        {
                            Id = 117,
                            Description = "D16",
                            ImgUri = "https://placeholder.com/16",
                            Name = "P16",
                            Price = 13.02m
                        },
                        new
                        {
                            Id = 118,
                            Description = "D17",
                            ImgUri = "https://placeholder.com/17",
                            Name = "P17",
                            Price = 92.24m
                        },
                        new
                        {
                            Id = 119,
                            Description = "D18",
                            ImgUri = "https://placeholder.com/18",
                            Name = "P18",
                            Price = 11.17m
                        },
                        new
                        {
                            Id = 120,
                            Description = "D19",
                            ImgUri = "https://placeholder.com/19",
                            Name = "P19",
                            Price = 64.34m
                        },
                        new
                        {
                            Id = 121,
                            Description = "D20",
                            ImgUri = "https://placeholder.com/20",
                            Name = "P20",
                            Price = 28.44m
                        },
                        new
                        {
                            Id = 122,
                            Description = "D21",
                            ImgUri = "https://placeholder.com/21",
                            Name = "P21",
                            Price = 76.32m
                        },
                        new
                        {
                            Id = 123,
                            Description = "D22",
                            ImgUri = "https://placeholder.com/22",
                            Name = "P22",
                            Price = 86.46m
                        },
                        new
                        {
                            Id = 124,
                            Description = "D23",
                            ImgUri = "https://placeholder.com/23",
                            Name = "P23",
                            Price = 35.84m
                        },
                        new
                        {
                            Id = 125,
                            Description = "D24",
                            ImgUri = "https://placeholder.com/24",
                            Name = "P24",
                            Price = 50.07m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
